{
  "name": "proxy-server",
  "version": "1.0.0",
  "main": "server.js",
  "dependencies": {
    "express": "^4.17.1",
    "http-proxy-middleware": "^2.0.1"
  },
  "scripts": {
    "start": "node server.js"
  }
}
